name: Scheduled Playwright Tests

on: 
  schedule:
    - cron: '0 0 * * *' # Scheduled to run at 00:00 UTC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Run Docker
        run: docker compose up -d
        
      - name: Install Playwright Browsers
        run: npm install @playwright/test && npx playwright install --with-deps
        
          # Run all in directory
      # - name: Run Playwright tests
      #   run: npx playwright test tests/admin/landingPage
      
          # Run only one
      # - name: Run Playwright tests
      #   run: npx playwright test tests/admin/landingPage/visibility.spec.js
      
          # Run all tests
      - name: Run Playwright tests
        run: npx playwright test
      
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
